import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import cart from "./assets/cart.svg"
import logo from "./assets/logo.svg"
import map from "./assets/map.svg"
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='h-10 mx-40 my-8 flex justify-between'>
          <Image src={logo} width={85} height={40} alt='' />
          <div className='flex gap-3'>
            <span className='flex'><Image src={map} width={22} height={22} alt='' />Porto Alegre</span>
            <Image src={cart} width={22} height={22} alt='' />
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
